### ISSUE TITLE
SSH 报文损坏，切换成功率低

### ISSUE THREAD

**Issue by kings-way** [oowl/quicssh-rs#1]
【测试环境 1 】
本地：电信宽带，同光猫下的几个 WiFi 路由器，轮流切换；
远程：vps，延迟约 140 ms，当前丢包情况为 0%，连接建立后在 vps 上持续 ping 1.1.1.1
                        
【测试环境 2 】
本地：联通 5G 手机热点，轮流打开 “网络数据” 开关
远程：vps，延迟约 170 多 ms，当前丢包情况为 0%，连接建立后在 vps 上持续 ping 1.1.1.1

以上两种环境多次测试，SSH 连接漫游只成功过一次，**甚至有时候连上 ssh 没有任何操作，几秒之后也会自动断开** ；
手机热点的测试，在很短时间内开关数据，本机持续 ping 测试确认网络很快恢复，但是 SSH 连接都会断开，错误如下：
```
Bad packet length 3414441652.
ssh_dispatch_run_fatal: Connection to UNKNOWN port 65535: Connection corrupted
```

在客户端发生错误、连接断开之后，服务端才会出现 read error 错误并关闭相应连接
```
ERROR quicssh_rs::server - [server] reading from quic client error: connection lost`
INFO quicssh_rs::server - [server] exit client
```

所以是 SSH 连接先断开，之后 QUIC 连接才断开，猜测是否是连接重建过程中，错误发送了 buffer 中的部分数据导致破坏了 SSH 报文？

**Comment by oowl** [comment]
fixed https://github.com/oowl/quicssh-rs/releases/tag/v0.1.1
