### ISSUE TITLE
`env_logger` has bad chemistry with `ProxyCommmand`

### ISSUE THREAD

**Issue by JyJyJcr** [oowl/quicssh-rs#10]
`env_logger` found to have two conflicts with `ProxyCommand`.
1. `ProxyCommand` not support environment variable. 
    `ProxyCommand` cannot execute command lines with variable setting like this:
    ```zsh
    $ cat ~/.ssh/config
    ...
    ProxyCommand RUST_LOG=off /path/to/quicssh-rs client quic://%h:%p
    ...
    ```
    There are several workarounds:
    1. wrapping command line by `sh -c`:
        ```zsh
        $ cat ~/.ssh/config
        ...
        ProxyCommand sh -c "RUST_LOG=off /path/to/quicssh-rs client quic://%h:%p"
        ...
        ```
        this would work at any environment, but if `dash` is used as `sh`, `ssh` will keep an unused `dash` process between the `quicssh-rs` process.
    2. setting `RUST_LOG` in advance:
        ```zsh
        $ cat ~/.zshrc
        ...
        export RUST_LOG=off
        ...
        ```
        but it would affect other rust programs using `RUST_LOG`.
    3. setting an unique variable in advance (with small change of code):
        ```zsh
        $ cat ~/.zshrc
        ...
        export QUICSSH_RS_LOG=off
        ...
        ```
        this has no effect on other porgrams. but I think this is a bad fix which split one configuration into two files.
2. unable to redirect stdout.
    usually stdout from `ProxyCommand` shows when `-v` option setted.
    ```zsh
    $ cat ~/.ssh/config
    ...
    Host test
    ProxyCommand echo aaa
    ...
    
    $ ssh test
    Connection closed by UNKNOWN port 65535
    
    $ ssh test -v
    ...
    debug1: Executing proxy command: exec echo aaa
    ...
    debug1: kex_exchange_identification: banner line 0: aaa
    ...
    ```
    however, for unknown reason, `env_logger` pass the logs not to `ssh` but directly to stdout, which results in uncontrolled log messages displayed. 
    ```zsh
    $ cat ~/.ssh/config
    ...
    Host test
    ProxyCommand /path/to/quicssh-rs client quic://%h:%p
    ...
    
    $ ssh test
    [xxxx-xx-xxTxx:xx:xxZ INFO  quicssh_rs::client] [client] Connecting to xxx.xxx.xxx.xxx:xxxxx
    [xxxx-xx-xxTxx:xx:xxZ INFO  quicssh_rs::client] [client] connected: addr=xxx.xxx.xxx.xxx:xxxxx
    ```

**Comment by oowl** [comment]
Yeah, I forgot something that quichssh relay on stdin and stdout for ssh proxy, So if we print log directly to stdout or stderr, Maybe it's not a good idea, because it can not log anything if we are using quicssh-rs in proxy (file log it's a better way to do this)

**Comment by oowl** [comment]
Maybe we need to restore env_logger to https://github.com/oowl/quicssh-rs/pull/8/commits/393a81e945800cf803e93f9d08f81dca8a460c79

**Comment by JyJyJcr** [comment]
I agree to recover file logging for recording.

In addition, we should log to stderr without log file specified. it is not used for proxying, and ssh client also prints the log into it.
In the first comment I reported banner line debug print:
```
debug1: kex_exchange_identification: banner line 0: aaa
```
but it is caused by the proxy's log printed into stdout, not stderr. the banner is originally sent from server, but in this case the log message is misunderstood as a part of the banner. printig into stderr doesn't cause this.

**Comment by oowl** [comment]
@JyJyJcr I think it seems you have resolved your problem now. So could you close this issue?
